
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./projects:/var/www/html"
    restart: always
    environment:
      - NGINX_HOST=localhost
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - docker-vpc
    depends_on:
        - php

  php:
    image: nanoninja/php-fpm:8.1
    container_name: php
    restart: always
    volumes:
        - "./projects:/var/www/html"
    networks:
        - docker-vpc

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=localhost
        - APACHE_PORT=8100
    restart: always
    ports:
      - "8100:8100"
    networks:
        - docker-vpc
    depends_on:
      - mysql

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      - MYSQL_VERSION=8.2
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - "./mysql/data:/var/lib/mysql"
    networks:
        - docker-vpc
    ports:
      - "8306:3306"

networks:
  docker-vpc:
    driver: bridge
